/* Generated by Yosys 0.33 (git sha1 2584903a060) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "counter.v:2.1-22.10" *)
module counter(clk, rst_n, clr, en, q);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  (* src = "counter.v:5.16-5.19" *)
  (* sta_arrival = "0" *)
  input clk;
  wire clk;
  (* src = "counter.v:7.16-7.19" *)
  (* sta_arrival = "0" *)
  input clr;
  wire clr;
  (* src = "counter.v:8.16-8.18" *)
  (* sta_arrival = "0" *)
  input en;
  wire en;
  (* src = "counter.v:9.28-9.29" *)
  output [7:0] q;
  wire [7:0] q;
  (* src = "counter.v:6.16-6.21" *)
  (* sta_arrival = "0" *)
  input rst_n;
  wire rst_n;
  sky130_fd_sc_hd__clkinv_1 _23_ (
    .A(q[6]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21oi_1 _24_ (
    .A1(q[0]),
    .A2(en),
    .B1(clr),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o21a_1 _25_ (
    .A1(q[0]),
    .A2(en),
    .B1(_09_),
    .X(_00_)
  );
  sky130_fd_sc_hd__and3_1 _26_ (
    .A(q[0]),
    .B(q[1]),
    .C(en),
    .X(_10_)
  );
  sky130_fd_sc_hd__a21oi_1 _27_ (
    .A1(q[0]),
    .A2(en),
    .B1(q[1]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor3_1 _28_ (
    .A(clr),
    .B(_10_),
    .C(_11_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _29_ (
    .A(q[2]),
    .B(_10_),
    .Y(_12_)
  );
  sky130_fd_sc_hd__and4_1 _30_ (
    .A(q[0]),
    .B(q[1]),
    .C(q[2]),
    .D(en),
    .X(_13_)
  );
  sky130_fd_sc_hd__nor3_1 _31_ (
    .A(clr),
    .B(_12_),
    .C(_13_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__and2_0 _32_ (
    .A(q[3]),
    .B(_13_),
    .X(_14_)
  );
  sky130_fd_sc_hd__nor2_1 _33_ (
    .A(q[3]),
    .B(_13_),
    .Y(_15_)
  );
  sky130_fd_sc_hd__nor3_1 _34_ (
    .A(clr),
    .B(_14_),
    .C(_15_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__xnor2_1 _35_ (
    .A(q[4]),
    .B(_14_),
    .Y(_16_)
  );
  sky130_fd_sc_hd__nor2_1 _36_ (
    .A(clr),
    .B(_16_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__nand4_1 _37_ (
    .A(q[3]),
    .B(q[4]),
    .C(q[5]),
    .D(_13_),
    .Y(_17_)
  );
  sky130_fd_sc_hd__a31oi_1 _38_ (
    .A1(q[3]),
    .A2(q[4]),
    .A3(_13_),
    .B1(q[5]),
    .Y(_18_)
  );
  sky130_fd_sc_hd__nor2_1 _39_ (
    .A(clr),
    .B(_18_),
    .Y(_19_)
  );
  sky130_fd_sc_hd__and2_0 _40_ (
    .A(_17_),
    .B(_19_),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _41_ (
    .A(_08_),
    .B(_17_),
    .Y(_20_)
  );
  sky130_fd_sc_hd__nor2_1 _42_ (
    .A(clr),
    .B(_20_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o21ai_0 _43_ (
    .A1(_08_),
    .A2(_17_),
    .B1(q[7]),
    .Y(_21_)
  );
  sky130_fd_sc_hd__or3_1 _44_ (
    .A(_08_),
    .B(q[7]),
    .C(_17_),
    .X(_22_)
  );
  sky130_fd_sc_hd__a21oi_1 _45_ (
    .A1(_21_),
    .A2(_22_),
    .B1(clr),
    .Y(_07_)
  );
  (* src = "counter.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _46_ (
    .CLK(clk),
    .D(_00_),
    .Q(q[0]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _47_ (
    .CLK(clk),
    .D(_01_),
    .Q(q[1]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _48_ (
    .CLK(clk),
    .D(_02_),
    .Q(q[2]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _49_ (
    .CLK(clk),
    .D(_03_),
    .Q(q[3]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _50_ (
    .CLK(clk),
    .D(_04_),
    .Q(q[4]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _51_ (
    .CLK(clk),
    .D(_05_),
    .Q(q[5]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _52_ (
    .CLK(clk),
    .D(_06_),
    .Q(q[6]),
    .RESET_B(rst_n)
  );
  (* src = "counter.v:12.5-20.8" *)
  sky130_fd_sc_hd__dfrtp_1 _53_ (
    .CLK(clk),
    .D(_07_),
    .Q(q[7]),
    .RESET_B(rst_n)
  );
endmodule
